id: alien4cloud-rms-scheduler-plugin
name: RMS Scheduler Plugin
version: ${project.version}
description: >
  A rule based scheduler that launch workflows.
configuration_class: org.alien4cloud.rmsscheduler.RMSPluginContextConfiguration
ui_entry_point: scripts/plugin.js
component_descriptors:
  - bean_name: rms-scheduler-modifier
    name: RMS Scheduler Modifier
    description: >
      Detect RMS policies and prepare Drools to run them.
  - bean_name: rule-condition-suggestion-provider
    name: Rule condition suggestion provider
    description: >
      Propose sentences from DSL to end user to enter rule conditions
  - bean_name: workflow-suggestion-provider
    name: Worklfow name suggestion
    description: >
      Propose all current topology workflows
